services:
  - type: web
    name: ecoscan-yolo-api
    runtime: docker
    plan: free

    dockerfilePath: ./Dockerfile

    healthCheckPath: /health

    envVars:
      - key: DEVICE
        value: cpu

      - key: CONFIDENCE
        value: "0.35"

      - key: IOU
        value: "0.45"

      - key: IMG_SIZE
        value: "224"

      - key: MAX_FILE_SIZE
        value: "1500000"

      - key: MAX_IMAGE_DIMENSION
        value: "960"

      - key: MAX_DETECTIONS
        value: "20"

      - key: ALLOWED_ORIGIN
        value: "*"
