services:
  - type: web
    name: ecoscan-yolo-api
    runtime: docker
    plan: free

    dockerfilePath: ./Dockerfile

    healthCheckPath: /health

    envVars:
      - key: DEVICE
        value: cpu

      - key: CONFIDENCE
        value: "0.35"

      - key: IOU
        value: "0.45"

      - key: IMG_SIZE
        value: "512"

      - key: ALLOWED_ORIGIN
        value: "*"